test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  service: S3
  access_key_id: <%= ENV['IAM_AWS_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['IAM_AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['AWS_REGION'] %>
  bucket: <%= ENV['AWS_BUCKET'] %>
  # Enable public access for CDN
  public: false
  upload:
    cache_control: "public, max-age=31536000, immutable"

mirror:
  service: Mirror
  primary: local
  mirrors: [ amazon ]